name = "daves-pipes-leaderboard"
main = "src/index.js"
compatibility_date = "2024-12-01"

kv_namespaces = [
  { binding = "LEADERBOARD_KV", id = "REPLACE_WITH_KV_ID", preview_id = "REPLACE_WITH_PREVIEW_ID" }
]
